### ISSUE TITLE
Test on Vuly

### ISSUE THREAD

**Issue by kennedyrose** [escaladesports/react-escalade-priceline#3]
> I just got off the phone with a woman trying to order a trampoline, basketball set, and ladder from the VulyPlay website for the PEN. I was walking her through step by step and she was running into a couple issues. She is on a desktop.
>  
> The “Add to Cart” button and price isn’t appearing in Safari, even after a refresh on the trampolines page (https://www.vulyplay.com/trampolines) .
> After having added the trampoline, basketball set, and ladder and going through the checkout process she’s running into more issues. After entering all of her credit card info, it’s taking her back to her cart, where it is removing the ladder and basketball toss. It’s only leaving the Lift XL in there and then she’s having to enter all that info again only to run into the same problem. She said she tried to do it about 10 times on Safari, and then I tried walking her through it on Chrome and Firefox to come up with the same result.

**Comment by tbaustin** [comment]
I tested all this in safari and it seems to be working to me. The only reason I can think of it removing items would be that they don't exist on the check when they submit their info to the api, but I think that this all is working for me fine on safari when I tested it. Do we have a repo for the vuly site?

**Comment by tbaustin** [comment]
Tested, works on modern browsers, but not older ones.

**Comment by tbaustin** [comment]
The items being removed is most likely due too a case issue with the products ids.
